-- Default email templates have no author.
--
-- `created_by` was NOT NULL, which meant a template could only exist once a
-- user did — and no user exists until someone signs in. So a fresh install had
-- no templates, and with no templates an offer cannot be sent at all (it needs
-- `offer_letter_html`, which is rendered from one) and the rejection dialog's
-- "send email" switch can never be satisfied. Both of the product's
-- candidate-facing emails were unreachable out of the box.
--
-- Nullable rather than pointing the seeded rows at some arbitrary user: a
-- template the installation provided was not written by anyone, and saying so
-- is more honest than attributing it to whoever happened to sign in first.
ALTER TABLE "templates" ALTER COLUMN "created_by" DROP NOT NULL;
